export const abilityColors: { [key: string]: string } = {
  fire: "orange",
  water: "lightblue",
  psychic: "purple",
  grass: "green",
  electric: "yellow",
  flying: "#555",
  insect: "",
  normal: "white",
  poison: "lilac",
  fighter: "brown",
  rock: "#333",
};

export const abilityTypeMapping: { [key: string]: string[] } = {
  grass: [
    "chlorophyll",
    "overgrow",
    "effect-spore",
    "leaf-guard",
    "flower-gift",
    "grass-pelt",
  ],
  fire: [
    "blaze",
    "solar-power",
    "flash-fire",
    "flare-boost",
    "heatproof",
    "magician",
  ],
  water: [
    "torrent",
    "rain-dish",
    "hydration",
    "shell-armor",
    "liquid-ooze",
    "weak-armor",
  ],
  psychic: [
    "cute-charm",
    "friend-guard",
    "magic-guard",
    "unaware",
    "frisk",
    "synchronize",
  ],
  electric: [
    "lightning-rod",
    "static",
    "volt-absorb",
    "motor-drive",
    "minus",
    "plus",
  ],
  flying: [
    "big-pecks",
    "keen-eye",
    "tangled-feet",
    "rain-dish",
    "gale-wings",
    "weak-armor",
  ],
  insect: [
    "sniper",
    "swarm",
    "run-away",
    "shields-down",
    "quick-feet",
    "run-away",
  ],
  normal: [
    "run-away",
    "shield-dust",
    "drought",
    "reckless",
    "sheer-force",
    "simple",
  ],
  poison: [
    "intimidate",
    "shed-skin",
    "unnerve",
    "poison-point",
    "tinted-lens",
    "rivalry",
    "stall",
  ],
  fighter: ["sand-rush", "sand-veil", "damp", "dry-skin", "guts", "iron-fist"],
  rock: [
    "torrent",
    "rain-dish",
    "sturdy",
    "rock-head",
    "reckless",
    "weak-armor",
  ],
};
