export const abilityColors: { [key: string]: string } = {
  fire: "orange",
  water: "lightblue",
  psychic: "purple",
  grass: "green",
  electric: "yellow",
  flying: "#555",
  insect: "#b5f600",
  normal: "white",
  poison: "lilac",
  fighter: "brown",
  rock: "#333",
};

export const abilityTypeMapping: { [key: string]: string[] } = {
  grass: [
    "chlorophyll",
    "overgrow",
    "effect-spore",
    "leaf-guard",
    "flower-gift",
    "grass-pelt",
    "aqua-boost",
    "aroma-veil",
    "chlorophyll",
    "effect-spore",
    "leaf-guard",
    "sap-sipper",
    "seed-sower",
    "tangled-feet",
  ],
  fire: [
    "blaze",
    "solar-power",
    "flash-fire",
    "flare-boost",
    "heatproof",
    "magician",
    "anger-point",
    "anger-shell",
    "emergency-exit",
    "flame-body",
    "flame-boost",
    "flare-boost",
    "flash-fire",
    "magma-armor",
    "reckless",
  ],
  water: [
    "torrent",
    "rain-dish",
    "hydration",
    "shell-armor",
    "liquid-ooze",
    "weak-armor",
    "aqua-boost",
    "comatose",
    "damp",
    "drizzle",
    "dry-skin",
    "early-bird",
    "hydration",
    "liquid-voice",
    "rain-dish",
    "shell-armor",
    "storm-drain",
    "water-absorb",
    "water-bubble",
    "water-compaction",
    "water-veil",
  ],
  psychic: [
    "cute-charm",
    "friend-guard",
    "magic-guard",
    "unaware",
    "frisk",
    "synchronize",
    "analytic",
    "anticipation",
    "comatose",
    "forewarn",
    "frisk",
    "inner-focus",
    "magic-bounce",
    "magic-guard",
    "magician",
    "natural-cure",
    "synchronize",
  ],
  electric: [
    "lightning-rod",
    "static",
    "volt-absorb",
    "motor-drive",
    "minus",
    "plus",
    "electric-surge",
    "electromorphosis",
    "galvanize",
    "motor-drive",
    "transistor",
  ],
  flying: [
    "big-pecks",
    "keen-eye",
    "tangled-feet",
    "rain-dish",
    "gale-wings",
    "weak-armor",
    "aerilate",
    "cloud-nine",
    "delta-stream",
    "flame-body",
    "frisk",
    "gale-wings",
    "gluttony",
    "honey-gather",
    "keen-eye",
    "pressure",
    "reckless",
    "tangled-feet",
  ],
  insect: [
    "sniper",
    "swarm",
    "run-away",
    "shields-down",
    "quick-feet",
    "run-away",
    "anticipation",
    "compound-eyes",
    "effect-spore",
    "insomnia",
    "mimicry",
    "run-away",
    "shield-dust",
    "skill-link",
    "swarm",
  ],
  normal: [
    "run-away",
    "shield-dust",
    "drought",
    "reckless",
    "sheer-force",
    "simple",
    "adaptability",
    "ball-fetch",
    "cheek-pouch",
    "cute-charm",
    "friend-guard",
    "gluttony",
    "guts",
    "hustle",
    "immunity",
    "inner-focus",
    "keen-eye",
    "pickup",
    "pixilate",
    "prankster",
    "quick-feet",
    "rattled",
    "reckless",
    "serene-grace",
    "sheer-force",
    "simple",
    "skill-link",
    "tangled-feet",
    "thick-fat",
    "unaware",
    "unburden",
  ],
  poison: [
    "intimidate",
    "shed-skin",
    "unnerve",
    "poison-point",
    "tinted-lens",
    "rivalry",
    "stall",
    "aftermath",
    "corrosion",
    "gooey",
    "immunity",
    "liquid-ooze",
    "merciless",
    "mold-breaker",
    "neutralizing-gas",
    "poison-heal",
    "poison-touch",
    "stench",
    "toxic-boost",
  ],
  fighter: [
    "sand-rush",
    "sand-veil",
    "damp",
    "dry-skin",
    "guts",
    "iron-fist",
    "anger-point",
    "battle-armor",
    "battle-bond",
    "defiant",
    "moxie",
    "pure-power",
    "quick-feet",
    "steadfast",
    "vital-spirit",
  ],
  rock: [
    "torrent",
    "rain-dish",
    "sturdy",
    "rock-head",
    "reckless",
    "weak-armor",
    "battle-armor",
    "hard-rock",
    "lightning-rod",
    "magnet-pull",
    "power-spot",
    "sand-force",
    "sand-rush",
    "sand-spit",
    "sand-stream",
    "sand-veil",
    "sturdy",
  ],
};
